function msg = psyrat_admissibility_note(adm)
%Turn an admissibility record into text a user can act on
%
%msg = psyrat_admissibility_note(adm)
%
%Inputs
% adm - diagnostic struct built by psyrat_admissibility (may be [] or a
%  struct array of them, e.g. one per group/event cell)
%
%Outputs
% msg - char row explaining what happened, or '' when there is nothing to
%  report
%
%Contract
% Returns '' for a clean result, for an empty input, and for any malformed or
% legacy struct. This mirrors psyrat_convergence_notice and psyrat_engine_notice:
% a caller can always display the result unconditionally, and a run with nothing
% wrong produces byte-identical output to before this diagnostic existed.
%
%Only the notable case is described. A quantity that is a perfectly ordinary
%positive variance contributes nothing to the message.

% Copyright (C) 2016-2026 Peter E. Clayson
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     any later version.
%
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
%     GNU General Public License for more details.
%
%     You should have received a copy of the GNU General Public License
%     along with this program (gpl.txt). If not, see
%     <http://www.gnu.org/licenses/>.
%

msg = '';

%fail open on anything unexpected, exactly as the provenance and convergence
%readers do: a diagnostic must never be the reason an export or a viewer breaks
if isempty(adm) || ~isstruct(adm)
    return;
end

%accept either a single record or an array of them (one per group/event cell)
entries = struct('label',{},'fcn',{},'role',{},'ndraw',{},'nneg',{},'nzero',{},...
    'minval',{});
for k = 1:numel(adm)
    if isfield(adm(k),'entries') && ~isempty(adm(k).entries)
        e = adm(k).entries;
        %the role field arrived after the rest of the record (RC-37). Backfill
        %it on anything written without one, so a legacy record still returns
        %text rather than throwing from the concatenation below. 'numerator' is
        %the wording every record received before the field existed.
        if ~isfield(e,'role')
            [e.role] = deal('numerator');
        end
        entries = [entries, e]; %#ok<AGROW> one small append per cell
    end
end

if isempty(entries)
    return;
end

neg = entries([entries.nneg] > 0);
zer = entries([entries.nzero] > 0 & [entries.nneg] == 0);

if isempty(neg) && isempty(zer)
    return;
end

lines = {};

if ~isempty(neg)
    %roll up repeated labels: the same quantity is recorded once per
    %group/event cell, and a user wants "how much of the posterior", not a
    %list of every cell
    [labels,~,idx] = unique({neg.label});
    lines{end+1} = ['NOT INTERPRETABLE AS A RELIABILITY: one or more quantities ',...
        'that must be variances came out negative.'];
    lines{end+1} = '';
    for k = 1:numel(labels)
        sel = neg(idx == k);
        lines{end+1} = sprintf('  %s: negative in %d of %d draws (most negative %.4g), in %s', ...
            labels{k}, sum([sel.nneg]), sum([sel.ndraw]), min([sel.minval]), ...
            strjoin(unique({sel.fcn}),', ')); %#ok<AGROW>
    end
    lines{end+1} = '';
    lines{end+1} = [...
        'A raw variance of a difference is non-negative whenever the cross-condition ',...
        'block is a real covariance matrix, so there are two possible causes and they ',...
        'call for different responses. Which one applies depends on the numbers of ',...
        'observations this was evaluated at -- something you know and this message ',...
        'does not.'];
    lines{end+1} = '';
    lines{end+1} = [...
        '(1) THE D-STUDY PROJECTION, if the two conditions were evaluated at ',...
        'DIFFERENT numbers of observations. Each variance is divided by its own ',...
        'number of observations while the covariance between the two conditions is ',...
        'divided by their HARMONIC mean (Rocha et al., 2026, Table 6). Because the ',...
        'harmonic mean falls below the geometric mean whenever the two counts differ, ',...
        'that subtraction can exceed the variances it is taken from. On this cause ',...
        'the estimated variance components are NOT at fault.'];
    lines{end+1} = '';
    lines{end+1} = [...
        '(2) A CROSS-CONDITION BLOCK THAT IS NOT A COVARIANCE MATRIX, if the two ',...
        'conditions were evaluated at the SAME number of observations. There the ',...
        'harmonic, geometric and arithmetic means coincide and every projected block ',...
        'reduces to the raw block divided by its own count, so if every raw block ',...
        'were a valid covariance structure each term would be non-negative and this ',...
        'could not happen. The projection ALONE therefore cannot be the cause: at ',...
        'least one raw block is already inadmissible. In this toolbox that arises in ',...
        'the gamma / scaled-chi-square family, whose variance diagonals are clamped ',...
        'at zero while the matching cross-covariances are not.'];
    lines{end+1} = '';
    lines{end+1} = [...
        'Note for case (2): the counts still govern whether you SEE it. The ',...
        'quantities above are SUMS of blocks carrying different divisors (the trial ',...
        'count, the occasion count, and their product), so no single factor cancels ',...
        'out. Changing the common count can hide or reveal the same faulty block ',...
        'without changing anything about your data. A warning that goes away when ',...
        'you raise or lower n has not been fixed.'];
    lines{end+1} = '';
    lines{end+1} = [...
        'The coefficient shown is the formula evaluated exactly, and nothing has been ',...
        'clipped or replaced. It is reported so you can see what happened, but it is ',...
        'not interpretable as a reliability and should not be reported as one.'];
    lines{end+1} = '';
    lines{end+1} = [...
        'What to do. If the two counts DIFFER, re-evaluate the difference score with ',...
        'the SAME number of observations for both conditions, where the harmonic, ',...
        'geometric and arithmetic means coincide and cause (1) cannot arise. If they ',...
        'were already EQUAL, cause (1) is ruled out and re-running at equal counts ',...
        'will not help; treat the estimated components themselves as suspect. One ',...
        'further signature of cause (1): if an intraclass correlation is shown ',...
        'alongside and looks ordinary, it is computed at a single observation and is ',...
        'unaffected by the projection, which localizes the problem to the projection ',...
        'rather than to your data.'];
end

if ~isempty(zer)
    if ~isempty(lines)
        lines{end+1} = '';
    end
    [labels,~,idx] = unique({zer.label});
    for k = 1:numel(labels)
        sel = zer(idx == k);
        %Exactly zero means opposite things in the two positions, so the
        %wording follows the role the quantity was recorded under. A label
        %names one quantity taken from one position, so the role is constant
        %within a group and the first entry speaks for all of them.
        if strcmp(sel(1).role,'denominator')
            lines{end+1} = sprintf(['Note: the %s was exactly zero in %d of %d ',...
                'draws. This is a real result rather than a fault -- error ',...
                'components that are perfectly correlated with equal variance ',...
                'cancel in the difference score, leaving no error of that kind. ',...
                'Note the DIRECTION: an error variance of zero drops that term ',...
                'from the denominator and pushes the coefficient toward one, not ',...
                'toward zero. Read it as an extreme estimate rather than as a ',...
                'perfect measurement, because a variance component clamped at ',...
                'zero during estimation produces the same value.'], ...
                labels{k}, sum([sel.nzero]), sum([sel.ndraw])); %#ok<AGROW>
        else
            lines{end+1} = sprintf(['Note: the %s was exactly zero in %d of %d draws. ',...
                'This is a real result rather than a fault -- two conditions that are ',...
                'perfectly correlated with equal variance produce a difference score ',...
                'with no between-person variance, and a reliability of zero is then the ',...
                'correct answer.'], labels{k}, sum([sel.nzero]), sum([sel.ndraw])); %#ok<AGROW>
        end
    end
end

msg = strjoin(lines, newline);

end
