classdef TestNonconcurrentDodReliability < matlab.unittest.TestCase
    %TESTNONCONCURRENTDODRELIABILITY The one-facet per-participant stage-3
    % calculator (analysis 28, PSYRAT_SSREL_DODIFFDYNREL_GAMMA_LS) against the
    % FROZEN EXTERNAL ORACLE: the reference bundle's own stage-3 output on the
    % deterministic one-facet lane (tests/baselines/nonconcurrent_dod,
    % provenance-hashed; generated by the owner's independent R
    % implementation, never by this code).
    %
    % Every quantity the reference emits per draw x participant x design is
    % verified: the three component matrices (via the assembler), the
    % unscaled and harmonic-scaled composites, both coefficients, the
    % matched-facet ICCs, the per-cell person quantities (expected scores,
    % residual SDs, person-conditional nu), the residual-sum-of-four identity
    % (reference check 8), and the posterior_invalid flags. Exact-shared
    % columns exist in the fixture but are out of toolbox scope
    % (harmonic-only owner ruling, 2026-08-12) and are deliberately not read.
    %
    % Tolerances: RelTol 1e-9 with an AbsTol 1e-12 floor. Two sources of
    % difference are expected and bounded well below that: the CSV decimal
    % round-trip (~15 significant digits) and the product-identity vs
    % subtraction grouping of the mean-surface cross terms (the toolbox's
    % PSYRAT_GAMMA_CROSSCOV_RESCOR note documents the regrouping).

    properties (Constant)
        Lane = 'onefacet';
    end

    methods (Test)

        function testComponentsMatchFrozenReference(testCase)
            fx = localLoadLane(testCase.Lane);
            mats = localAssemble(fx);
            labels = fx.labels;
            comps = {'p','i','pi_e'};
            act = fx.actual;   %one design suffices: components are design-invariant
            for ci = 1:numel(comps)
                comp = comps{ci};
                for q = 1:4
                    got = localPick(mats.(comp), fx, 'diag', q);
                    want = act.(sprintf('var_%s_%s',labels{q},comp));
                    testCase.verifyEqual(got, want, 'RelTol', 1e-9, ...
                        'AbsTol', 1e-12, sprintf('var_%s_%s', labels{q}, comp));
                end
                for a = 1:3
                    for b = (a+1):4
                        got = localPick(mats.(comp), fx, 'cross', [a b]);
                        want = act.(sprintf('cov_%s__%s_%s',labels{a},labels{b},comp));
                        testCase.verifyEqual(got, want, 'RelTol', 1e-9, ...
                            'AbsTol', 1e-12, ...
                            sprintf('cov_%s__%s_%s', labels{a}, labels{b}, comp));
                    end
                end
                got = localPick(mats.(comp), fx, 'dod', []);
                want = act.(sprintf('var_dod_%s',comp));
                testCase.verifyEqual(got, want, 'RelTol', 1e-9, 'AbsTol', 1e-12, ...
                    sprintf('var_dod_%s', comp));
            end
        end

        function testCoefficientsMatchFrozenReference(testCase)
            fx = localLoadLane(testCase.Lane);
            [~, dl] = localRunCalculator(fx);

            act = fx.actual; stdz = fx.standardized;
            flat = @(m) m(:);   %draws x nsub in fixture row order (draw outer,
                                %person inner) after the transpose in localPick
            testCase.verifyEqual(flat(dl.u'), act.universe_dod, ...
                'RelTol', 1e-9, 'AbsTol', 1e-12, 'universe (actual)');
            testCase.verifyEqual(flat(dl.rel'), act.relative_error_dod, ...
                'RelTol', 1e-9, 'AbsTol', 1e-12, 'relative error (actual)');
            testCase.verifyEqual(flat(dl.abs_'), act.absolute_error_dod, ...
                'RelTol', 1e-9, 'AbsTol', 1e-12, 'absolute error (actual)');
            testCase.verifyEqual(flat(dl.G'), act.G_dod, ...
                'RelTol', 1e-9, 'AbsTol', 1e-12, 'G (actual)');
            testCase.verifyEqual(flat(dl.D'), act.D_dod, ...
                'RelTol', 1e-9, 'AbsTol', 1e-12, 'D (actual)');
            testCase.verifyEqual(flat(dl.iccg'), ...
                act.ICC_relative_matched_facet_dod, ...
                'RelTol', 1e-9, 'AbsTol', 1e-12, 'relative ICC');
            testCase.verifyEqual(flat(dl.iccd'), ...
                act.ICC_absolute_matched_facet_dod, ...
                'RelTol', 1e-9, 'AbsTol', 1e-12, 'absolute ICC');
            testCase.verifyEqual(flat(dl.invalid'), ...
                act.posterior_invalid_primary_any, 'AbsTol', 0, ...
                'invalid flag (actual): flags are exact, not approximate');

            testCase.verifyEqual(flat(dl.rel_std'), stdz.relative_error_dod, ...
                'RelTol', 1e-9, 'AbsTol', 1e-12, 'relative error (standardized)');
            testCase.verifyEqual(flat(dl.abs_std'), stdz.absolute_error_dod, ...
                'RelTol', 1e-9, 'AbsTol', 1e-12, 'absolute error (standardized)');
            testCase.verifyEqual(flat(dl.G_std'), stdz.G_dod, ...
                'RelTol', 1e-9, 'AbsTol', 1e-12, 'G (standardized)');
            testCase.verifyEqual(flat(dl.D_std'), stdz.D_dod, ...
                'RelTol', 1e-9, 'AbsTol', 1e-12, 'D (standardized)');
            testCase.verifyEqual(flat(dl.invalid_std'), ...
                stdz.posterior_invalid_primary_any, 'AbsTol', 0, ...
                'invalid flag (standardized)');
        end

        function testPersonQuantitiesMatchFrozenReference(testCase)
            fx = localLoadLane(testCase.Lane);
            [~, dl] = localRunCalculator(fx);
            act = fx.actual;
            labels = fx.labels;
            for q = 1:4
                testCase.verifyEqual(localFlatCell(dl.expected_pop, q), ...
                    act.(sprintf('expected_%s_population',labels{q})), ...
                    'RelTol', 1e-9, 'AbsTol', 1e-12, ...
                    sprintf('expected_%s_population', labels{q}));
                testCase.verifyEqual(localFlatCell(dl.expected_person, q), ...
                    act.(sprintf('expected_%s_person',labels{q})), ...
                    'RelTol', 1e-9, 'AbsTol', 1e-12, ...
                    sprintf('expected_%s_person', labels{q}));
                testCase.verifyEqual(localFlatCell(dl.sigma_person, q), ...
                    act.(sprintf('residual_sd_%s_person',labels{q})), ...
                    'RelTol', 1e-9, 'AbsTol', 1e-12, ...
                    sprintf('residual_sd_%s_person', labels{q}));
                testCase.verifyEqual(localFlatCell(dl.nu_person, q), ...
                    act.(sprintf('nu_%s_at_person_expected_mean',labels{q})), ...
                    'RelTol', 1e-9, 'AbsTol', 1e-12, ...
                    sprintf('nu_%s', labels{q}));
            end

            %reference check 8: the DoD residual variance is EXACTLY the sum
            %of the four per-cell residual variances (all six residual
            %covariances are zero), verified against the frozen reference in
            %the same row order as every other quantity.
            s4 = localFlatCell(dl.sigma_person.^2, 1) + ...
                localFlatCell(dl.sigma_person.^2, 2) + ...
                localFlatCell(dl.sigma_person.^2, 3) + ...
                localFlatCell(dl.sigma_person.^2, 4);
            testCase.verifyEqual(s4, act.residual_var_dod_person, ...
                'RelTol', 1e-9, 'AbsTol', 1e-12, ...
                'residual_var_dod_person vs frozen reference');
        end

        function testSsrelTableShape(testCase)
            %The production table contract: one row per participant, the
            %shared ssrel_table coefficient columns plus the standardized
            %twins and DoD extras, no NaN points on this clean fixture, and
            %actual/standardized genuinely different (the fixture's n' are
            %primes unequal to the actual counts).
            fx = localLoadLane(testCase.Lane);
            ssrel = localRunCalculator(fx);
            testCase.verifyEqual(height(ssrel), height(fx.persontable));
            need = {'gen_pt','gen_ll','gen_ul','dep_pt','dep_ll','dep_ul', ...
                'iccg_pt','iccd_pt','sem_gen_pt','sem_dep_pt', ...
                'gen_pt_std','dep_pt_std','uni_pt','relerr_pt','abserr_pt', ...
                'expected_dod_pop_pt','expected_dod_person_pt', ...
                'residual_var_dod_person_pt','nu1_pt','ressd4_pt', ...
                'invalid_frac','invalid_frac_std'};
            for i = 1:numel(need)
                testCase.verifyTrue(ismember(need{i}, ...
                    ssrel.Properties.VariableNames), ...
                    sprintf('ssrel must carry %s.', need{i}));
            end
            testCase.verifyTrue(all(isfinite(ssrel.gen_pt)));
            testCase.verifyTrue(all(ssrel.gen_pt ~= ssrel.gen_pt_std), ...
                'actual and standardized coefficients must differ per person.');
        end

        function testCouplingVocabularyRejected(testCase)
            %The nonconcurrent boundary at the calculator signature.
            for coupled = {'rho','rho_e','cov_e_obs','cov_res_e_obs','er_cov','rescor','copula'}
                testCase.verifyError(@() psyrat_ssrel_dodiffdynrel_gamma_ls( ...
                    coupled{1}, 0.3), ...
                    'psyrat_ssrel_dodiffdynrel_gamma_ls:noresidualcoupling');
                testCase.verifyError(@() psyrat_rel_dodiffdynrel_gamma_ls( ...
                    coupled{1}, 0.3), ...
                    'psyrat_rel_dodiffdynrel_gamma_ls:noresidualcoupling');
            end
        end

        function testSurfaceMatchesZeroEffectParticipant(testCase)
            %The typical-person surface at grid z must equal the
            %STANDARDIZED-design coefficients of a hypothetical participant
            %with ZERO person effects at that same z: both routes evaluate
            %the identical per-draw arithmetic (population signal at z,
            %population sigma at z, n' counts), so this is an exact internal
            %cross-check of the surface through the fixture-validated
            %per-participant calculator.
            fx = localLoadLane(testCase.Lane);
            zprobe = [-0.85 0 0.6];
            surf = psyrat_rel_dodiffdynrel_gamma_ls('b', fx.b, ...
                'b_sigma', fx.b_sigma, 'b_dim', fx.b_dim, ...
                'b_sigma_dim', fx.b_sigma_dim, 'sd_id', fx.sd_id, ...
                'cor_id', fx.cor_id, 'sd_trl', fx.sd_trl, ...
                'cor_trl', fx.cor_trl, 'ndim', 1, 'z1', zprobe, ...
                'obs', fx.nprime, 'CI', 0.95, 'cvec', fx.cvec);

            nz = numel(zprobe);
            fake = table((1:nz)', (1:nz)', zprobe(:), ...
                repmat(fx.idtable.trls1(1),nz,1), repmat(fx.idtable.trls2(1),nz,1), ...
                repmat(fx.idtable.trls3(1),nz,1), repmat(fx.idtable.trls4(1),nz,1), ...
                'VariableNames', {'id','id2','z1','trls1','trls2','trls3','trls4'});
            zero = struct();
            for q = 1:4
                zero.(sprintf('mu_ss%d',q)) = repmat(fx.b(:,q), 1, nz);
                zero.(sprintf('er_ss%d',q)) = repmat(fx.b_sigma(:,q), 1, nz);
            end
            ss = psyrat_ssrel_dodiffdynrel_gamma_ls('b', fx.b, ...
                'b_sigma', fx.b_sigma, 'b_dim', fx.b_dim, ...
                'b_sigma_dim', fx.b_sigma_dim, 'sd_id', fx.sd_id, ...
                'cor_id', fx.cor_id, 'sd_trl', fx.sd_trl, ...
                'cor_trl', fx.cor_trl, ...
                'mu_ss1', zero.mu_ss1, 'mu_ss2', zero.mu_ss2, ...
                'mu_ss3', zero.mu_ss3, 'mu_ss4', zero.mu_ss4, ...
                'er_ss1', zero.er_ss1, 'er_ss2', zero.er_ss2, ...
                'er_ss3', zero.er_ss3, 'er_ss4', zero.er_ss4, ...
                'idtable', fake, 'nprime', fx.nprime, ...
                'ndim', 1, 'CI', 0.95, 'cvec', fx.cvec);

            testCase.verifyEqual(ss.gen_pt_std, surf.G.pt(:), 'AbsTol', 1e-12, ...
                'Surface G must equal the zero-effect participant at n''.');
            testCase.verifyEqual(ss.dep_pt_std, surf.D.pt(:), 'AbsTol', 1e-12, ...
                'Surface D must equal the zero-effect participant at n''.');
            testCase.verifyEqual(ss.iccg_pt, surf.ICCg.pt(:), 'AbsTol', 1e-12, ...
                'Surface relative ICC must match (count-free).');
            testCase.verifyEqual(ss.iccd_pt, surf.ICCd.pt(:), 'AbsTol', 1e-12, ...
                'Surface absolute ICC must match (count-free).');
        end

        function testSummaryDispatch(testCase)
            %A synthetic analysis-28 REL (built from the frozen-fixture
            %arrays, stored in the engine's num2cell idiom) through
            %psyrat_dynrel_summary: the DoD branch must route, populate the
            %per-participant table, resolve the per-cell n' 4-vector, carry
            %the estimand labels and the invalidity counts, and fail loudly
            %by name on a wrong family stamp.
            fx = localLoadLane(testCase.Lane);
            REL = localSyntheticRel(fx);
            w = warning('off','dynrel:dodinvalidity');
            cleaner = onCleanup(@() warning(w));
            summ = psyrat_dynrel_summary(REL,'ngrid',5);

            testCase.verifyEqual(numel(summ.strata), 1);
            st = summ.strata(1);
            testCase.verifyEqual(numel(st.obs_ev), 4, ...
                'The DoD stratum must carry a per-cell n'' 4-vector.');
            testCase.verifyEqual(st.obs_ev, ...
                max(1,round([5 7 5 7])), ...
                'Default n'' must be the stored per-cell medians.');
            testCase.verifyEqual(height(st.ssrel_table), fx.P, ...
                'One per-participant row per person.');
            testCase.verifyTrue(ismember('gen_pt', ...
                st.ssrel_table.Properties.VariableNames));
            testCase.verifyTrue(all(isfinite(st.G.pt(:))), ...
                'The typical-person surface must be populated.');
            testCase.verifyEqual(summ.dod_labels.inference_framework, ...
                'modular_four_gamma_margins_all_residual_covariances_fixed_zero_v1');
            testCase.verifyTrue(st.dod_flags.recorded);
            testCase.verifyTrue(st.dod_flags.flags_complete);
            testCase.verifyEmpty(st.copula_flags, ...
                'No copula machinery may touch a nonconcurrent DoD result.');
            testCase.verifyEmpty(st.quaddiag);

            %fail-loud by name on a non-location-scale arrival. Since the
            %Gaussian arm shipped (2026-08-20) a family = 'gaussian' stamp is
            %ACCEPTED - its routing pin lives in
            %TestNonconcurrentDodGaussReliability - so the rejection arms here
            %are the stamps that remain invalid: an explicit log-nu gamma
            %stamp, and a REL with no family stamp at all (the damaged-file
            %arrival the case-13 fall-through note is about).
            RELbad = REL;
            RELbad.gammascale = 1;
            testCase.verifyError(@() psyrat_dynrel_summary(RELbad), ...
                'dynrel:dodgammals');
            RELnofam = rmfield(REL, 'family');
            testCase.verifyError(@() psyrat_dynrel_summary(RELnofam), ...
                'dynrel:dodgammals');
        end

        function testProvenanceDisclosure(testCase)
            %psyrat_provenance_lines on a DoD result must emit the
            %nonconcurrent disclosure block (framework, counterfactual
            %estimand, location-scale estimand, validity pointer) and NOT the
            %modular-cut block; a result without dod_labels must emit
            %neither. The negative halves keep the presence-keying honest.
            fx = localLoadLane(testCase.Lane);
            REL = localSyntheticRel(fx);
            %psyrat_provenance_lines takes the GUI's wrapper struct and
            %unwraps .rel (a bare REL yields the not-recorded legacy block)
            lines = psyrat_provenance_lines(struct('rel', REL));
            txt = strjoin(string(lines), ' | ');
            testCase.verifyTrue(contains(txt, ...
                'modular_four_gamma_margins_all_residual_covariances_fixed_zero_v1'), ...
                'The framework token must be quoted from the stored labels.');
            testCase.verifyTrue(contains(txt, ...
                'NONCONCURRENT COUNTERFACTUAL ESTIMAND'), ...
                'The counterfactual-estimand line must be present.');
            testCase.verifyTrue(contains(txt, 'LOCATION-SCALE'), ...
                'The location-scale estimand line must be present.');
            testCase.verifyTrue(contains(txt, 'record-never-repair'), ...
                'The validity pointer must be present.');
            testCase.verifyFalse(contains(txt, 'CUT posterior'), ...
                'The modular-cut disclosure must NOT fire (no copula exists).');

            %DEGRADED MODE: without the labels the block falls back to the
            %string-keyed counterfactual disclosure (never fully silent on a
            %DoD result - the one disclosure the estimand makes mandatory),
            %but the framework token, which only the labels carry, is absent.
            RELbare = REL;
            RELbare.out = rmfield(RELbare.out, 'dod_labels');
            barelines = psyrat_provenance_lines(struct('rel', RELbare));
            baretxt = strjoin(string(barelines), ' | ');
            testCase.verifyTrue(contains(baretxt, ...
                'NONCONCURRENT COUNTERFACTUAL ESTIMAND'), ...
                ['Without dod_labels the degraded string-keyed disclosure ' ...
                'must still fire.']);
            testCase.verifyTrue(contains(baretxt, 'labels missing'), ...
                'The degraded line must say the labels are missing.');
            testCase.verifyFalse(contains(baretxt, ...
                'modular_four_gamma_margins_all_residual_covariances_fixed_zero_v1'), ...
                'The framework token exists only in the stored labels.');
            %and a NON-DoD result emits neither form
            RELother = REL;
            RELother.analysis = 'ic_diff_dynrel_sserrvar';
            RELother.out = rmfield(RELother.out, 'dod_labels');
            otherlines = psyrat_provenance_lines(struct('rel', RELother));
            testCase.verifyFalse(contains(strjoin(string(otherlines), ' | '), ...
                'NONCONCURRENT COUNTERFACTUAL ESTIMAND'), ...
                'A non-DoD analysis string must not trigger the fallback.');
        end

        function testDisclosureHelpers(testCase)
            %psyrat_dod_labels: presence-keyed, well-formedness requires
            %inference_framework; psyrat_dod_flag_counts: exact rescaled
            %counts, absence of evidence distinguishable from evidence of
            %absence.
            lab = struct('inference_framework','modular_four_gamma_margins_all_residual_covariances_fixed_zero_v1');
            out = struct('dod_labels', lab);
            got = psyrat_dod_labels(out);
            testCase.verifyEqual(got.inference_framework, lab.inference_framework);
            testCase.verifyEmpty(psyrat_dod_labels(struct('other',1)));
            testCase.verifyEmpty(psyrat_dod_labels(struct('dod_labels', ...
                struct('note','malformed - no framework field'))));

            fx = localLoadLane(testCase.Lane);
            ssrel = localRunCalculator(fx);
            flags = psyrat_dod_flag_counts(ssrel, fx.nd);
            testCase.verifyTrue(flags.recorded);
            testCase.verifyTrue(flags.flags_complete);
            testCase.verifyEqual(flags.n_evals, height(ssrel) * fx.nd);
            testCase.verifyEqual(flags.n_invalid, ...
                round(sum(ssrel.invalid_frac) * fx.nd));

            empty = psyrat_dod_flag_counts([], fx.nd);
            testCase.verifyFalse(empty.recorded);
            partial = psyrat_dod_flag_counts( ...
                removevars(ssrel, 'invalid_frac_std'), fx.nd);
            testCase.verifyTrue(partial.recorded);
            testCase.verifyFalse(partial.flags_complete, ...
                'A missing design column must clear flags_complete.');
        end

        function testReportEstimandNoteDegradedFallback(testCase)
            %B15: the export estimand note is presence-keyed on the dod_labels
            %carrier with NO degraded fallback, so a DoD result missing the
            %carrier (damaged or pre-release stored file) falls through to the
            %gamma location-scale branch and claims the MARGINAL estimand
            %("population average over person residual-SD heterogeneity") --
            %the exact mislabel the pre-merge review fixed on the populated
            %path. The provenance block already degrades string-keyed for the
            %identical condition (testProvenanceDisclosure above); the
            %estimand note must do the same: decline to assert an estimand and
            %say why, never claim marginal (or typical-person) wording it
            %cannot support. Headless surface: psyrat_report's estimand_note.
            fx = localLoadLane(testCase.Lane);
            REL = localSyntheticRel(fx);
            pd = localReportData(REL);
            w = warning('off', 'dynrel:dodinvalidity');
            cleaner = onCleanup(@() warning(w));

            %populated control: the typical-person sentence must be intact,
            %and the marginal wording absent (pins the daf3509 fix).
            rep = psyrat_report(pd);
            testCase.assertTrue(contains(rep.estimand_note, 'typical person'), ...
                'populated control broken: the typical-person sentence is gone');
            testCase.verifyFalse(contains(rep.estimand_note, ...
                'population average'), ...
                'populated control broken: the marginal wording appeared');

            %degraded arm: strip the carrier, as a damaged stored result would.
            pdbare = pd;
            pdbare.rel.out = rmfield(pdbare.rel.out, 'dod_labels');
            repbare = psyrat_report(pdbare);
            testCase.verifyFalse(contains(repbare.estimand_note, ...
                'population average'), ...
                ['B15: the degraded note claims the marginal location-scale ' ...
                'estimand these designs do not report']);
            testCase.verifyFalse(contains(repbare.estimand_note, ...
                'typical person'), ...
                ['B15: the degraded note asserts the typical-person estimand ' ...
                'without the carrier that vouches for it']);
            testCase.verifyTrue(contains(repbare.estimand_note, 'dod_labels'), ...
                'the degraded note must name the missing carrier');
        end

        function testViewerHeaderEstimandDegradedFallback(testCase)
            %B15, viewer surface: psyrat_startview_dynrel duplicates the
            %estimand branching ("Mirrors psyrat_report"), so the report-level
            %pin above does not cover it. Drive the viewer headlessly and read
            %the written variance-table CSV header on both arms.
            fx = localLoadLane(testCase.Lane);
            REL = localSyntheticRel(fx);
            pd = localReportData(REL);
            w = warning('off', 'dynrel:dodinvalidity');
            cleaner = onCleanup(@() warning(w));
            shadowCleaner = localInstallSaveShadow(); %#ok<NASGU>

            %populated control
            fig = localDodViewerFig(testCase, pd);
            figCleaner = onCleanup(@() close(fig, 'force'));
            csvfile = [tempname '.csv'];
            localFireDodSave(testCase, fig, csvfile);
            txt = fileread(csvfile);
            delete(csvfile);
            testCase.assertTrue(contains(txt, 'typical person'), ...
                'populated control broken: viewer header lost the typical-person line');
            testCase.verifyFalse(contains(txt, 'population average'), ...
                'populated control broken: viewer header carries the marginal wording');
            clear figCleaner

            %degraded arm
            pdbare = pd;
            pdbare.rel.out = rmfield(pdbare.rel.out, 'dod_labels');
            fig = localDodViewerFig(testCase, pdbare);
            figCleaner = onCleanup(@() close(fig, 'force'));
            csvfile = [tempname '.csv'];
            localFireDodSave(testCase, fig, csvfile);
            txt = fileread(csvfile);
            delete(csvfile);
            testCase.verifyFalse(contains(txt, 'population average'), ...
                ['B15: the degraded viewer header claims the marginal ' ...
                'location-scale estimand these designs do not report']);
            testCase.verifyFalse(contains(txt, 'typical person'), ...
                'B15: the degraded viewer header asserts the typical-person estimand');
            testCase.verifyTrue(contains(txt, 'dod_labels'), ...
                'the degraded viewer header must name the missing carrier');
        end

        function testZeroCountCellIsFlooredNotFatal(testCase)
            %B16: a participant with ZERO trials in one DoD cell must not
            %take down the whole per-participant summary. Pre-fix, the raw
            %count reached psyrat_dod_composite's n > 0 guard unfloored, so
            %the summary errored before any window was drawn and five of the
            %six viewer buttons failed identically for the WHOLE sample. The
            %floor mirrors the two-event sibling (psyrat_ssrel_diff:
            %obs = max(1, trls)): the empty cell computes at n = 1, the most
            %conservative finite count, while ssrel keeps the participant's
            %true zero. Preflight (dodPersonMissingCell) rejects such data
            %on the GUI path; this is defence in depth for the officially
            %supported programmatic route.
            fx = localLoadLane(testCase.Lane);
            fz = fx;
            fz.idtable.trls2(1) = 0;
            ssrel = localRunCalculator(fz);
            testCase.verifyTrue(all(isfinite(ssrel.gen_pt)) && ...
                all(isfinite(ssrel.dep_pt)), ...
                'a zero-count cell must yield finite floored coefficients');

            %floor semantics: exactly the arithmetic of an explicit n = 1
            f1 = fx;
            f1.idtable.trls2(1) = 1;
            want = localRunCalculator(f1);
            testCase.verifyEqual(ssrel.gen_pt, want.gen_pt, ...
                'the floored zero must compute exactly as n = 1');
            testCase.verifyEqual(ssrel.dep_pt, want.dep_pt, ...
                'the floored zero must compute exactly as n = 1');

            %the floor applies to the composite input only
            testCase.verifyEqual(ssrel.trls2(1), 0, ...
                'the output table must keep the participant''s true zero');
        end

        function testFlooredRowIsDisclosedByNFloored(testCase)
            %B16 residual (2026-08-18): keeping the true zero is right, but on
            %its own it left the export ambiguous -- a row showed trls2 = 0
            %beside a coefficient computed at n = 1 with nothing saying the
            %substitution happened. n_floored counts the substituted cells so
            %the disclosure travels with the row into both the GUI export
            %(psyrat_startview_dynrel/exportDynrelTable, which writes the table
            %verbatim) and the headless one (psyrat_report).
            fx = localLoadLane(testCase.Lane);

            %negative control FIRST: a clean fixture must report zero, or a
            %column that is always nonzero would pass the positive case for
            %the wrong reason
            clean = localRunCalculator(fx);
            testCase.verifyTrue(ismember('n_floored', ...
                clean.Properties.VariableNames), ...
                'the disclosure column must exist on every row, not only floored ones');
            testCase.verifyEqual(unique(clean.n_floored), 0, ...
                'no cell was empty, so nothing may be reported as floored');

            %one empty cell
            f1 = fx;
            f1.idtable.trls2(1) = 0;
            one = localRunCalculator(f1);
            testCase.verifyEqual(one.n_floored(1), 1, ...
                'one substituted cell must be disclosed as exactly one');
            testCase.verifyEqual(one.trls2(1), 0, ...
                'the count column must still carry the true zero');

            %two empty cells in the same participant, and untouched neighbours
            f2 = fx;
            f2.idtable.trls2(1) = 0;
            f2.idtable.trls3(1) = 0;
            two = localRunCalculator(f2);
            testCase.verifyEqual(two.n_floored(1), 2, ...
                'n_floored must COUNT the substituted cells, not merely flag them');
            if height(two) > 1
                testCase.verifyEqual(two.n_floored(2), 0, ...
                    'a participant with no empty cell must stay at zero');
            end
        end

        function testFloorCoversExactlyTheEmptyCellZero(testCase)
            %B16 hardening (refuter-driven, 2026-08-17): the floor's
            %envelope must be EXACTLY the real zero. A max(1,...) floor
            %would also capture corrupt counts -- MATLAB's two-input max
            %OMITS NaN, so max(1,NaN) is silently 1, and negatives floor
            %the same way -- hiding them from psyrat_dod_composite's
            %n > 0 guard, which pre-B16 errored loudly on every one of
            %them. The repo's own convention two files away
            %(psyrat_dynrel_summary, 'reject a non-finite n'' BEFORE the
            %max(1,...) floor') exists for precisely this trap. Corrupt
            %counts are broken inputs, not degenerate data: they must
            %still error.
            fx = localLoadLane(testCase.Lane);

            fnan = fx;
            fnan.idtable.trls2(1) = NaN;
            testCase.verifyError(@() localRunCalculator(fnan), 'varargin:n', ...
                'a NaN count must still raise the composite guard, not floor to 1');

            fneg = fx;
            fneg.idtable.trls2(1) = -3;
            testCase.verifyError(@() localRunCalculator(fneg), 'varargin:n', ...
                'a negative count must still raise the composite guard, not floor to 1');

            %fractional counts in (0,1) were computable pre-B16 and must
            %keep their own arithmetic; the explicit-1 arm is the positive
            %control (if the floor wrongly engaged, the two would be equal
            %and this assertion could not fail)
            fh = fx;
            fh.idtable.trls2(1) = 0.5;
            half = localRunCalculator(fh);
            f1 = fx;
            f1.idtable.trls2(1) = 1;
            one = localRunCalculator(f1);
            testCase.verifyNotEqual(half.gen_pt(1), one.gen_pt(1), ...
                'a 0.5 count must keep its own arithmetic, not floor to 1');
        end

    end
end

% ---------------------------------------------------------------------------
% Fixture loading: reconstruct the calculator inputs from the frozen lane.
% ---------------------------------------------------------------------------

function fx = localLoadLane(lane)
here = fileparts(mfilename('fullpath'));
root = fullfile(here, 'baselines', 'nonconcurrent_dod');
rd = @(n) readtable(fullfile(root, sprintf('nonconcurrent_dod_%s_%s.csv', ...
    lane, n)), 'VariableNamingRule', 'preserve');

meta = rd('meta');
draws = rd('draws');
fx.persontable = rd('persontable');
expected = rd('stage3_expected');
fx.actual = sortrows(expected(strcmp(expected.design,'actual'),:), ...
    {'posterior_row','p_index'});
fx.standardized = sortrows(expected(strcmp(expected.design,'standardized'),:), ...
    {'posterior_row','p_index'});

fx.nd = meta.n_draws;
fx.K = meta.K;
fx.P = meta.P;
fx.labels = {char(meta.outcome_1), char(meta.outcome_2), ...
    char(meta.outcome_3), char(meta.outcome_4)};
fx.cvec = [meta.w1 meta.w2 meta.w3 meta.w4];
fx.mu_offset = [meta.mu_offset_1 meta.mu_offset_2 meta.mu_offset_3 meta.mu_offset_4];
fx.log_sigma_offset = [meta.log_sigma_offset_1 meta.log_sigma_offset_2 ...
    meta.log_sigma_offset_3 meta.log_sigma_offset_4];
%constituent order is (error, correct, error, correct), so the per-condition
%standardized counts expand to per-cell counts as (err, cor, err, cor)
fx.nprime = [meta.n_i_error_std meta.n_i_correct_std ...
    meta.n_i_error_std meta.n_i_correct_std];

par = @(nm) localParam(draws, nm);
fx.b = fx.mu_offset + par('alpha_mu');                       %absolute
fx.b_sigma = fx.log_sigma_offset + par('alpha_sigma');       %absolute
fx.b_dim = localParam3(draws, 'beta_mu', fx.K);
fx.b_sigma_dim = localParam3(draws, 'beta_sigma', fx.K);
fx.sd_id = localParamWide(draws, 'sd_p_joint', 8);
fx.cor_id = localParamMat(draws, 'R_p_joint', 8);
fx.sd_trl = localParamWide(draws, 'sd_i', 4);
fx.cor_trl = localParamMat(draws, 'R_i', 4);
u_p = localParamMat(draws, 'u_p_joint', [fx.P 8]);
for q = 1:4
    fx.(sprintf('mu_ss%d',q)) = fx.b(:,q) + u_p(:,:,q);
    fx.(sprintf('er_ss%d',q)) = fx.b_sigma(:,q) + u_p(:,:,4+q);
end

pt = fx.persontable;
fx.idtable = table(pt.ID, pt.p_index, pt.Dim1_z, ...
    pt.n_i_error_actual, pt.n_i_correct_actual, ...
    pt.n_i_error_actual, pt.n_i_correct_actual, ...
    'VariableNames', {'id','id2','z1','trls1','trls2','trls3','trls4'});
fx.ndim = 1;
end

function REL = localSyntheticRel(fx)
%A synthetic analysis-28 REL built from the frozen-fixture arrays in the
%engine's storage idiom ({num2cell(...)} per stratum), sufficient for the
%summary branch.
REL = struct();
REL.analysis = 'ic_dodiff_dynrel_sserrvar';
REL.family = 'gamma';
REL.gammascale = 2;
REL.ndim = 1;
REL.dim_names = {'dim1'};
out = struct();
out.labels = {'none'};
out.b = {num2cell(fx.b)};
out.b_sigma = {num2cell(fx.b_sigma)};
out.b_dim = {num2cell(fx.b_dim)};
out.b_sigma_dim = {num2cell(fx.b_sigma_dim)};
out.sd_id = {num2cell(fx.sd_id)};
out.sd_trl = {num2cell(fx.sd_trl)};
out.cor_id = {num2cell(fx.cor_id)};
out.cor_trl = {num2cell(fx.cor_trl)};
for q = 1:4
    out.(sprintf('mu_ss%d',q)) = {num2cell(fx.(sprintf('mu_ss%d',q)))};
    out.(sprintf('er_var_ss%d',q)) = {num2cell(fx.(sprintf('er_ss%d',q)))};
end
out.ssinfo = {fx.idtable};
out.dimz = {fx.idtable.z1};
out.ntrials = [5;7;5;7];   %per-cell medians (I_error=5, I_correct=7)
out.elabels = fx.labels(:);
out.glabels = {'none'};
out.dod_labels = struct(...
    'inference_framework',...
    'modular_four_gamma_margins_all_residual_covariances_fixed_zero_v1',...
    'cut_posterior_status',...
    'no_dependence_module_exists_because_all_constituents_are_assumed_nonconcurrent',...
    'residual_dependence_structure',...
    'all six pairwise conditional residual covariances fixed exactly to zero',...
    'scale_parameterization','person_specific_log_absolute_residual_sd',...
    'estimand_version','signed_four_component_nonconcurrent_dod_v1');
REL.out = out;
end

function pd = localReportData(REL)
%Wrap the synthetic REL as the psyrat_data struct the report and viewer
%surfaces consume, with the provenance/header fields the export headers read
%(the summary-only synthetic REL does not include them). Mirrors
%TestExportCallbacks' localAddSaveHeaderFields; kept local because the two
%classes pin different properties and a shared fixture would couple them.
pd = struct();
pd.rel = REL;
pd.ver = 'test';
pd.rel.filename = 'nonconcurrent_dod_fixture.psyrat';
pd.rel.nchains = 2;
pd.rel.niter = 600;
pd.rel.seed = 12345;
pd.rel.engine = 'cmdstan';
pd.rel.priors = psyrat_default_priors;
pd.rel.out.conv.converged = 1;
pd.rel.out.conv.ndivergent = 0;
end

function fig = localDodViewerFig(testCase, pd)
%Launch the dynamic-reliability viewer headlessly and return its figure
%(located by window name rather than by Tag). Same idiom as
%TestExportCallbacks' localDynrelViewerFig.
name = 'Dynamic Reliability: View Results';
close(findall(0, 'Type', 'figure', 'Name', name));
psyrat_startview_dynrel('psyrat_prefs', psyrat_defaults(), 'psyrat_data', pd);
fig = findall(0, 'Type', 'figure', 'Name', name);
testCase.assertNotEmpty(fig, 'Dynrel viewer figure not created');
fig = fig(1);
end

function cleaner = localInstallSaveShadow()
%Shadow uiputfile with a stub that auto-answers the save dialog from the
%PSYRAT_FAKE_SAVE global -- headless save callbacks would otherwise error
%(uiputfile blocks are unsupported under -batch). Same idiom as
%TestExportCallbacks' setupSaveShadow; the returned onCleanup removes the
%shadow and its temp folder.
shadowdir = tempname;
mkdir(shadowdir);
fid = fopen(fullfile(shadowdir, 'uiputfile.m'), 'w');
fprintf(fid, '%s\n', ...
    'function [filename,pathname,filterindex] = uiputfile(varargin)', ...
    '% TEST SHADOW: auto-answers the save dialog from a global.', ...
    'global PSYRAT_FAKE_SAVE', ...
    '[p,n,e] = fileparts(PSYRAT_FAKE_SAVE);', ...
    'filename = [n e]; pathname = [p filesep]; filterindex = 1;', ...
    'end');
fclose(fid);
addpath(shadowdir, '-begin');
rehash;
cleaner = onCleanup(@() localRemoveSaveShadow(shadowdir));
end

function localRemoveSaveShadow(shadowdir)
rmpath(shadowdir);
rehash;
if exist(shadowdir, 'dir')
    rmdir(shadowdir, 's');
end
end

function localFireDodSave(testCase, fig, outfile)
%Fire the 'Save variance table (CSV)' button through the PSYRAT_FAKE_SAVE
%test seam. The DoD viewer also carries a per-participant save button, so
%the label fragment names the variance one explicitly.
global PSYRAT_FAKE_SAVE %#ok<GVMIS> -- the uiputfile shadow's test seam
PSYRAT_FAKE_SAVE = outfile;
btns = findall(fig, 'Style', 'pushbutton');
fired = false;
for b = btns(:)'
    s = b.String; if iscell(s), s = strjoin(s, ' '); end
    if contains(string(s), 'Save variance')
        cb = b.Callback;
        cb(b, []);
        fired = true;
        break;
    end
end
PSYRAT_FAKE_SAVE = [];
testCase.assertTrue(fired, 'Save variance table button not found');
testCase.assertTrue(isfile(outfile), 'The variance CSV was not written');
end

function [ssrel, dl] = localRunCalculator(fx)
[ssrel, dl] = psyrat_ssrel_dodiffdynrel_gamma_ls('b', fx.b, ...
    'b_sigma', fx.b_sigma, 'b_dim', fx.b_dim, ...
    'b_sigma_dim', fx.b_sigma_dim, 'sd_id', fx.sd_id, 'cor_id', fx.cor_id, ...
    'sd_trl', fx.sd_trl, 'cor_trl', fx.cor_trl, ...
    'mu_ss1', fx.mu_ss1, 'mu_ss2', fx.mu_ss2, ...
    'mu_ss3', fx.mu_ss3, 'mu_ss4', fx.mu_ss4, ...
    'er_ss1', fx.er_ss1, 'er_ss2', fx.er_ss2, ...
    'er_ss3', fx.er_ss3, 'er_ss4', fx.er_ss4, ...
    'idtable', fx.idtable, 'nprime', fx.nprime, ...
    'ndim', fx.ndim, 'CI', 0.95, 'cvec', fx.cvec);
end

function mats = localAssemble(fx)
%Per-participant component matrices, stacked in fixture row order (draw
%outer, person inner), by rebuilding each participant's alpha / own sigma
%exactly as the calculator does and calling the assembler directly.
nd = fx.nd; P = fx.P;
mats = struct('p', [], 'i', [], 'pi_e', []);
stack = struct('p', zeros(nd*P,4,4), 'i', zeros(nd*P,4,4), ...
    'pi_e', zeros(nd*P,4,4));
for c = 1:P
    zt = fx.idtable.z1(c);
    alpha = zeros(nd,4); lsig_own = zeros(nd,4);
    for q = 1:4
        dimterm = reshape(fx.b_dim(:,q,:),nd,[]) * zt;
        sigterm = reshape(fx.b_sigma_dim(:,q,:),nd,[]) * zt;
        alpha(:,q) = fx.b(:,q) + dimterm;
        lsig_own(:,q) = fx.(sprintf('er_ss%d',q))(:,fx.idtable.id2(c)) + sigterm;
    end
    m = psyrat_gamma_dod_components_ls('facet','trial', ...
        'alpha', alpha, 'log_sigma', lsig_own, ...
        'sd_p', fx.sd_id(:,1:4), 'cor_p', fx.cor_id(:,1:4,1:4), ...
        'sd_trl', fx.sd_trl, 'cor_trl', fx.cor_trl);
    %row order: draw outer, person inner => row (d-1)*P + c
    idx = (0:nd-1)*P + c;
    for key = {'p','i','pi_e'}
        stack.(key{1})(idx,:,:) = m.(key{1});
    end
end
mats = stack;
mats.cvec = fx.cvec;
end

function v = localPick(stackmat, fx, kind, which)
%Column extraction from the stacked component matrices, in fixture row order.
switch kind
    case 'diag'
        v = stackmat(:, which, which);
    case 'cross'
        v = stackmat(:, which(1), which(2));
    case 'dod'
        %the frozen var_dod_* columns carry the reference's tiny-negative
        %floor; the kernel reproduces its semantics exactly
        c = psyrat_dod_composite('varcov', stackmat, 'cvec', fx.cvec, ...
            'rule', 'unscaled');
        v = c.value;
end
v = v(:);
end

function v = localFlatCell(arr3, q)
%[ndraws x 4 x nsub] -> fixture row order (draw outer, person inner).
x = squeeze(arr3(:, q, :));   %ndraws x nsub
xt = x';                      %nsub x ndraws
v = xt(:);
end

function v = localParam(draws, nm)
%[ndraws x 4] from the long-format draws fixture (idx1 = cell).
sub = draws(strcmp(draws.param, nm), :);
nd = max(sub.draw);
v = zeros(nd, 4);
for i = 1:height(sub)
    v(sub.draw(i), sub.idx1(i)) = sub.value(i);
end
end

function v = localParamWide(draws, nm, k)
%[ndraws x k] vector parameter.
sub = draws(strcmp(draws.param, nm), :);
nd = max(sub.draw);
v = zeros(nd, k);
for i = 1:height(sub)
    v(sub.draw(i), sub.idx1(i)) = sub.value(i);
end
end

function v = localParam3(draws, nm, K)
%[ndraws x 4 x K] matrix parameter (idx1 = cell, idx2 = dimension term).
sub = draws(strcmp(draws.param, nm), :);
nd = max(sub.draw);
v = zeros(nd, 4, K);
for i = 1:height(sub)
    v(sub.draw(i), sub.idx1(i), sub.idx2(i)) = sub.value(i);
end
end

function v = localParamMat(draws, nm, k)
%[ndraws x k x k] (square) or [ndraws x r x c] matrix parameter.
if isscalar(k), k = [k k]; end
sub = draws(strcmp(draws.param, nm), :);
nd = max(sub.draw);
v = zeros(nd, k(1), k(2));
for i = 1:height(sub)
    v(sub.draw(i), sub.idx1(i), sub.idx2(i)) = sub.value(i);
end
end
