classdef TestNonconcurrentDodStanBoundary < PsyRATTestBase
    %TESTNONCONCURRENTDODSTANBOUNDARY The scientific boundary of the
    % person-specific dynamic NONCONCURRENT difference-of-differences Stan
    % programs (analyses 28/29), asserted on the committed goldens.
    %
    % The defining property of these designs is a NEGATIVE one that no numeric
    % regression test can see: NOTHING in the model estimates residual
    % coupling. All six pairwise observation-level residual covariances are
    % fixed to exactly zero by the estimand (the four constituents are treated
    % as measured on distinct trials), and unlike the modular cut-copula
    % designs (19/20) there is no stage-2 dependence module either - the
    % posterior is the FULL Bayesian posterior of four conditionally
    % independent margins, not a cut posterior. An "improvement" that added a
    % copula, a residual correlation, or a joint observation density would
    % silently change the estimand; this class is what makes that loud.
    % (Ports of reference bundle checks 2-3, run_static_validation.R; the
    % bundle's own boundary is verified by its self-check, this one by ours.)
    %
    % This pins the GOLDENS; TestStanModelSnapshots separately requires the
    % goldens to equal the live builder output. Neither alone would suffice
    % (the copula boundary class records the same division of labor).

    properties (Constant)
        % One golden family per analysis; the __threaded twin is derived.
        Goldens = { ...
            'dynrel_gamma_ls_dodiff_sserr_onefacet.stan', ...
            'dynrel_gamma_ls_dodiff_sserr_trt_onefacet.stan' ...
            };

        % Forbidden tokens: the reference's set (gamma CDFs, the inverse
        % normal, copula vocabulary) plus the toolbox's coupling vocabulary
        % (Lrescor = the Gaussian concurrent coupling; multi_normal = a joint
        % observation density; rho_e = any sampled residual correlation).
        Forbidden = { ...
            'gamma_lcdf', 'gamma_lccdf', 'inv_Phi', 'copula', 'rho_e', ...
            'Lrescor', 'multi_normal' ...
            };
    end

    methods (Test)

        function testForbiddenTokensAbsent(testCase)
            for g = 1:numel(testCase.Goldens)
                for form = localForms(testCase.Goldens{g})
                    code = localReadGolden(testCase, form{1});
                    for t = 1:numel(testCase.Forbidden)
                        tok = testCase.Forbidden{t};
                        testCase.verifyEmpty(strfind(code, tok), sprintf( ...
                            ['%s: forbidden token ''%s'' found. Nothing in ' ...
                            'this design may estimate residual coupling - ' ...
                            'the six residual covariances are fixed to zero ' ...
                            'by the estimand.'], form{1}, tok));
                    end
                end
            end
        end

        function testRequiredStructurePresent(testCase)
            %The four-margin joint structure the estimand requires: the exact
            %scaled-chi-square mean/SD parameterization with derived nu, the
            %8-D joint person block, the 4-D crossed-trial block, four-cell
            %indexing, offsets as data, and dimension slopes on BOTH
            %submodels.
            required = { ...
                'scaled_chi_square_lpdf', ...
                'nu = 2 * square(mu ./ sigma);', ...
                'cholesky_factor_corr[8] L_id', ...
                'cholesky_factor_corr[4] L_trl', ...
                'array[NOBS] int<lower=1,upper=4> cell', ...
                'vector[4] mu_offset', ...
                'vector[4] log_sigma_offset', ...
                'matrix[4, KDIM] b_dim', ...
                'matrix[4, KDIM] b_sigma_dim', ...
                'corr_matrix[8] cor_id', ...
                'corr_matrix[4] cor_trl' ...
                };
            for g = 1:numel(testCase.Goldens)
                for form = localForms(testCase.Goldens{g})
                    code = localReadGolden(testCase, form{1});
                    for t = 1:numel(required)
                        testCase.verifyTrue( ...
                            contains(code, required{t}), sprintf( ...
                            '%s: required structure ''%s'' is missing.', ...
                            form{1}, required{t}));
                    end
                    %the residual SD carries the person scale effect and
                    %nothing else facet-shaped: facet factors must appear in
                    %the mean accumulation only
                    testCase.verifyTrue( ...
                        contains(code, 'sigma[n] = log_sigma_offset[c] + b_sigma[c]'), ...
                        sprintf(['%s: the residual-SD accumulation changed; ' ...
                        'verify no facet factor touches sigma.'], form{1}));
                    for facetTok = {'r_trl', 'r_occ', 'r_tid', 'r_oid', 'r_to'}
                        testCase.verifyEmpty( ...
                            strfind(code, sprintf('sigma[n] += %s', facetTok{1})), ...
                            sprintf(['%s: facet factor %s must never touch ' ...
                            'the residual SD.'], form{1}, facetTok{1}));
                    end
                    %the two-facet program must carry all four additional
                    %crossed 4-D facet blocks
                    if contains(form{1}, '_trt_')
                        for blk = {'cholesky_factor_corr[4] L_occ', ...
                                'cholesky_factor_corr[4] L_tid', ...
                                'cholesky_factor_corr[4] L_oid', ...
                                'cholesky_factor_corr[4] L_to', ...
                                'corr_matrix[4] cor_occ', ...
                                'corr_matrix[4] cor_tid', ...
                                'corr_matrix[4] cor_oid', ...
                                'corr_matrix[4] cor_to'}
                            testCase.verifyTrue(contains(code, blk{1}), ...
                                sprintf('%s: two-facet block ''%s'' is missing.', ...
                                form{1}, blk{1}));
                        end
                    end
                end
            end
        end

    end
end

function forms = localForms(name)
base = erase(name, '.stan');
forms = {sprintf('%s.stan', base), sprintf('%s__threaded.stan', base)};
end

function code = localReadGolden(testCase, name)
f = fullfile(testCase.projectRoot(), 'tests', 'golden', 'stan', name);
testCase.assertTrue(isfile(f), sprintf( ...
    'Golden %s is missing; run TestStanModelSnapshots with refresh first.', name));
code = fileread(f);
end
