classdef TestVararginRangeGuards < PsyRATTestBase
    %G58/G59 regression pins. psyrat_relsummary required meascutoff (all
    %four family parse blocks), depcentmeas (sing block), and relcentmeas
    %(trt and trt_diff blocks) but never range-checked them, and none of
    %the consuming switches carries an otherwise arm -- so an out-of-range
    %value (e.g. meascutoff = 4) fell through the switches silently and
    %died far downstream as an undefined variable ('trlcutoff' on the
    %trial-cutoff routes; an unrecognized table variable on the sserr
    %routes). G58 added the membership guard at all four meascutoff parse
    %sites and G59 the same guard at the depcentmeas/relcentmeas sites, so
    %the failure is now the same argument error the validated siblings
    %(gcoeff, diffgcoeff, CI) raise, at the parse block, naming the input.
    %
    %The guards fire during argument parsing, BEFORE psyrat_data is read,
    %so these pins pass a minimal struct as psyrat_data on purpose: under
    %the pre-fix code the same call runs past the parse block and dies with
    %a DIFFERENT error identifier, which makes every verifyError here fail
    %decisively (counterfactual discrimination without a full fixture).
    %
    %Positive controls (the differential-assertion rule): the in-class
    %control asserts that all-valid values do NOT raise any of the three
    %guarded identifiers (discriminating an inverted or always-firing
    %guard), and the full completing runs live in the sibling classes that
    %exercise every family with valid values in the same suite (e.g.
    %TestUnreachableCutoffSentinel calls sing and trt with meascutoff 2 and
    %depcentmeas/relcentmeas 1 end to end).
    %
    %The sing block is shared by sing/sing_sserr/sing_diff/sing_diff_sserr,
    %so the sing pins cover all four labels; likewise trt_diff's block is
    %reached through the trt_diff route alone.

    methods (Test)

        function testMeascutoffOutOfRangeSing(testCase)
            testCase.verifyError(@() psyrat_relsummary( ...
                'psyrat_data', struct(), 'analysis', 'sing', ...
                'depcutoff', 0.70, 'meascutoff', 4, 'depcentmeas', 1), ...
                'varargin:meascutoff');
        end

        function testMeascutoffOutOfRangeTrtSserr(testCase)
            testCase.verifyError(@() psyrat_relsummary( ...
                'psyrat_data', struct(), 'analysis', 'trt_sserr', ...
                'gcoeff', 1, 'reltype', 3, 'depcutoff', 0.70, ...
                'meascutoff', 4), ...
                'varargin:meascutoff');
        end

        function testMeascutoffOutOfRangeTrt(testCase)
            testCase.verifyError(@() psyrat_relsummary( ...
                'psyrat_data', struct(), 'analysis', 'trt', ...
                'gcoeff', 1, 'reltype', 3, 'relcutoff', 0.70, ...
                'meascutoff', 4, 'relcentmeas', 1), ...
                'varargin:meascutoff');
        end

        function testMeascutoffOutOfRangeTrtDiff(testCase)
            testCase.verifyError(@() psyrat_relsummary( ...
                'psyrat_data', struct(), 'analysis', 'trt_diff', ...
                'gcoeff', 1, 'diffgcoeff', 1, 'reltype', 3, ...
                'relcutoff', 0.70, 'meascutoff', 4, 'relcentmeas', 1), ...
                'varargin:meascutoff');
        end

        function testMeascutoffVectorRefused(testCase)
            %Wave hardening: a bare ~any(x == [1 2 3]) is elementwise, so a
            %vector with one in-range element (even [1 2 3] itself) slips
            %past it; the guards therefore test length first. Pinned on the
            %exhaustive-slip case.
            testCase.verifyError(@() psyrat_relsummary( ...
                'psyrat_data', struct(), 'analysis', 'sing', ...
                'depcutoff', 0.70, 'meascutoff', [1 2 3], ...
                'depcentmeas', 1), ...
                'varargin:meascutoff');
        end

        function testMeascutoffEmptyRefusedWithNamedError(testCase)
            %Wave hardening: [] == [1 2 3] THROWS sizeDimensionsMustMatch
            %(MEASURED R2025b), so without the length short-circuit an empty
            %meascutoff died inside the guard with the wrong identifier.
            testCase.verifyError(@() psyrat_relsummary( ...
                'psyrat_data', struct(), 'analysis', 'sing', ...
                'depcutoff', 0.70, 'meascutoff', [], 'depcentmeas', 1), ...
                'varargin:meascutoff');
        end

        function testDepcentmeasOutOfRangeSing(testCase)
            testCase.verifyError(@() psyrat_relsummary( ...
                'psyrat_data', struct(), 'analysis', 'sing', ...
                'depcutoff', 0.70, 'meascutoff', 2, 'depcentmeas', 3), ...
                'varargin:depcentmeas');
        end

        function testRelcentmeasOutOfRangeTrt(testCase)
            testCase.verifyError(@() psyrat_relsummary( ...
                'psyrat_data', struct(), 'analysis', 'trt', ...
                'gcoeff', 1, 'reltype', 3, 'relcutoff', 0.70, ...
                'meascutoff', 2, 'relcentmeas', 3), ...
                'varargin:relcentmeas');
        end

        function testRelcentmeasOutOfRangeTrtDiff(testCase)
            testCase.verifyError(@() psyrat_relsummary( ...
                'psyrat_data', struct(), 'analysis', 'trt_diff', ...
                'gcoeff', 1, 'diffgcoeff', 1, 'reltype', 3, ...
                'relcutoff', 0.70, 'meascutoff', 2, 'relcentmeas', 3), ...
                'varargin:relcentmeas');
        end

        function testValidValuesDoNotTripTheGuards(testCase)
            %Positive control: with every guarded parameter valid, none of
            %the guarded identifiers may fire. The minimal psyrat_data means
            %each call still errors LATER (a data-access failure past the
            %parse block); the assertion is on the identifier, so an
            %inverted or always-firing guard fails here while the intended
            %guard passes.
            guarded = {'varargin:meascutoff', 'varargin:depcentmeas', ...
                'varargin:relcentmeas'};
            calls = { ...
                {'psyrat_data', struct(), 'analysis', 'sing', ...
                 'depcutoff', 0.70, 'meascutoff', 2, 'depcentmeas', 1}, ...
                {'psyrat_data', struct(), 'analysis', 'trt_sserr', ...
                 'gcoeff', 1, 'reltype', 3, 'depcutoff', 0.70, ...
                 'meascutoff', 2}, ...
                {'psyrat_data', struct(), 'analysis', 'trt', ...
                 'gcoeff', 1, 'reltype', 3, 'relcutoff', 0.70, ...
                 'meascutoff', 2, 'relcentmeas', 1}, ...
                {'psyrat_data', struct(), 'analysis', 'trt_diff', ...
                 'gcoeff', 1, 'diffgcoeff', 1, 'reltype', 3, ...
                 'relcutoff', 0.70, 'meascutoff', 2, 'relcentmeas', 1}};
            for k = 1:numel(calls)
                err = [];
                try
                    psyrat_relsummary(calls{k}{:});
                catch err
                end
                %anti-vacuity (wave): the minimal psyrat_data MUST produce a
                %downstream error, or this loop would assert nothing at all
                %-- a control that cannot fail is not a control.
                testCase.assertNotEmpty(err, sprintf( ...
                    ['call %d: the minimal fixture was expected to error ' ...
                    'past the parse block'], k));
                testCase.verifyFalse(ismember(err.identifier, guarded), ...
                    sprintf(['call %d: valid values must pass the ' ...
                    'range guards (got %s)'], k, err.identifier));
            end
        end

    end
end
