classdef TestNonconcurrentDodGaussStanBoundary < PsyRATTestBase
    %TESTNONCONCURRENTDODGAUSSSTANBOUNDARY The scientific boundary of the
    % GAUSSIAN person-specific dynamic NONCONCURRENT difference-of-differences
    % Stan programs (analyses 28/29, family='gaussian'), asserted on the
    % committed goldens. The gamma arm has its own class
    % (TestNonconcurrentDodStanBoundary); they are separate because the
    % required-structure sets are family-specific - the gamma class REQUIRES
    % the scaled-chi-square vocabulary this class FORBIDS.
    %
    % Two boundaries are pinned here:
    %  - THE NONCONCURRENT BOUNDARY (shared with the gamma arm): nothing in
    %    the model estimates residual coupling. All six pairwise
    %    observation-level residual covariances are fixed to exactly zero by
    %    the estimand, and there is no stage-2 dependence module - the
    %    posterior is the FULL Bayesian posterior of four conditionally
    %    independent margins, not a cut posterior.
    %  - THE FAMILY BOUNDARY: the observation likelihood is Normal with an
    %    IDENTITY-link mean (ERP scores may be negative; no exp touches mu, no
    %    offsets-as-data exist for this family) and a LOG-link residual SD. A
    %    chi-square token in a Gaussian golden is a family leak.
    %
    % This pins the GOLDENS; TestStanModelSnapshots separately requires the
    % goldens to equal the live builder output. Neither alone would suffice.

    properties (Constant)
        % One golden family per analysis; the __threaded twin is derived.
        Goldens = { ...
            'dynrel_dodiff_sserr_onefacet.stan', ...
            'dynrel_dodiff_sserr_trt_onefacet.stan' ...
            };

        % Forbidden tokens: the gamma class's coupling set, plus the family
        % boundary (scaled-chi-square vocabulary and the derived-nu line),
        % plus the gamma-lineage offsets-as-data device, plus the log-link
        % mean transform.
        Forbidden = { ...
            'gamma_lcdf', 'gamma_lccdf', 'inv_Phi', 'copula', 'rho_e', ...
            'Lrescor', 'multi_normal', ...
            'scaled_chi_square', 'nu = 2 * square', ...
            'mu_offset', 'log_sigma_offset', ...
            'mu = exp(mu);' ...
            };
    end

    methods (Test)

        function testForbiddenTokensAbsent(testCase)
            for g = 1:numel(testCase.Goldens)
                for form = localForms(testCase.Goldens{g})
                    code = localReadGolden(testCase, form{1});
                    for t = 1:numel(testCase.Forbidden)
                        tok = testCase.Forbidden{t};
                        testCase.verifyEmpty(strfind(code, tok), sprintf( ...
                            ['%s: forbidden token ''%s'' found. The Gaussian ' ...
                            'DoD margins are identity-link Normal with no ' ...
                            'residual coupling and no offsets-as-data.'], ...
                            form{1}, tok));
                    end
                end
            end
        end

        function testRequiredStructurePresent(testCase)
            %The four-margin joint structure the estimand requires under the
            %Gaussian family: a Normal likelihood, an identity-link mean, a
            %log-link residual SD, the 8-D joint person block, the 4-D
            %crossed-trial block, four-cell indexing, and dimension slopes on
            %BOTH submodels.
            required = { ...
                'normal_lpdf', ...
                'sigma = exp(sigma);', ...
                'mu[n] = b[c] + Xdim[n] * b_dim[c]''', ...
                'sigma[n] = b_sigma[c] + Xdim[n] * b_sigma_dim[c]''', ...
                'cholesky_factor_corr[8] L_id', ...
                'cholesky_factor_corr[4] L_trl', ...
                'array[NOBS] int<lower=1,upper=4> cell', ...
                'vector[NOBS] meas', ...
                'matrix[4, KDIM] b_dim', ...
                'matrix[4, KDIM] b_sigma_dim', ...
                'corr_matrix[8] cor_id', ...
                'corr_matrix[4] cor_trl' ...
                };
            for g = 1:numel(testCase.Goldens)
                for form = localForms(testCase.Goldens{g})
                    code = localReadGolden(testCase, form{1});
                    for t = 1:numel(required)
                        testCase.verifyTrue( ...
                            contains(code, required{t}), sprintf( ...
                            '%s: required structure ''%s'' is missing.', ...
                            form{1}, required{t}));
                    end
                    %the response must be UNSIGNED: a positivity bound on meas
                    %would silently re-impose the gamma family's support
                    testCase.verifyEmpty( ...
                        strfind(code, 'vector<lower=0>[NOBS] meas'), sprintf( ...
                        ['%s: the Gaussian response must not carry a ' ...
                        'positivity bound - negative cell means are the ' ...
                        'point of this arm.'], form{1}));
                    %the residual SD carries the person scale effect and
                    %nothing else facet-shaped: facet factors must appear in
                    %the mean accumulation only
                    for facetTok = {'r_trl', 'r_occ', 'r_tid', 'r_oid', 'r_to'}
                        testCase.verifyEmpty( ...
                            strfind(code, sprintf('sigma[n] += %s', facetTok{1})), ...
                            sprintf(['%s: facet factor %s must never touch ' ...
                            'the residual SD.'], form{1}, facetTok{1}));
                    end
                    testCase.verifyEmpty( ...
                        strfind(code, 'r_trl[TRL[n], 4 + c]'), sprintf( ...
                        ['%s: only the person block carries scale columns; ' ...
                        'a facet block must never index past column 4.'], ...
                        form{1}));
                    %the two-facet program must carry all four additional
                    %crossed 4-D facet blocks
                    if contains(form{1}, '_trt_')
                        for blk = {'cholesky_factor_corr[4] L_occ', ...
                                'cholesky_factor_corr[4] L_tid', ...
                                'cholesky_factor_corr[4] L_oid', ...
                                'cholesky_factor_corr[4] L_to', ...
                                'corr_matrix[4] cor_occ', ...
                                'corr_matrix[4] cor_tid', ...
                                'corr_matrix[4] cor_oid', ...
                                'corr_matrix[4] cor_to'}
                            testCase.verifyTrue(contains(code, blk{1}), ...
                                sprintf('%s: two-facet block ''%s'' is missing.', ...
                                form{1}, blk{1}));
                        end
                    end
                end
            end
        end

    end
end

function forms = localForms(name)
base = erase(name, '.stan');
forms = {sprintf('%s.stan', base), sprintf('%s__threaded.stan', base)};
end

function code = localReadGolden(testCase, name)
f = fullfile(testCase.projectRoot(), 'tests', 'golden', 'stan', name);
testCase.assertTrue(isfile(f), sprintf( ...
    'Golden %s is missing; run TestStanModelSnapshots with refresh first.', name));
code = fileread(f);
end
