function catalog = psyrat_formula_catalog(varargin)
%Return a quick-reference catalog of Table 2, 3, and 6 formulas.
%
%catalog = psyrat_formula_catalog
%catalog = psyrat_formula_catalog('analysis','sing')
%
%Optional input
% analysis - 'all' (default), 'sing', 'sing_diff', 'sing_sserr', 'trt',
%            'dynrel' (dynamic/conditional reliability, Rast & Clayson), or
%            'splits' (nonparallel splits observed design, Rocha Tables 4/5)

% Copyright (C) 2016-2025 Peter E. Clayson
%
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     any later version.
%
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
%     GNU General Public License for more details.
%
%     You should have received a copy of the GNU General Public License
%     along with this program (gpl.txt). If not, see
%     <http://www.gnu.org/licenses/>.

analysis = 'all';

if ~isempty(varargin)
    if mod(length(varargin),2)
        error('varargin:incomplete',... %Error code and associated error
            strcat('WARNING: Inputs are incomplete \n\n',...
            'Make sure each variable input is paired with a value \n'));
    end
    
    ind = find(strcmpi('analysis',varargin),1);
    if ~isempty(ind)
        analysis = varargin{ind+1};
    end
end

if isstring(analysis)
    analysis = char(analysis);
end

rows = {...
    't2_global_d','2','One-facet (p x i)','Global coefficient','Absolute (D)',...
    'D = bp^2 / (bp^2 + wp^2 / n)',...
    'psyrat_rel_sing',...
    'Formula Guide -> Run Formula',...
    'Implemented',...
    'Table 2 one-facet absolute global coefficient';...
    ...
    't2_global_g','2','One-facet (p x i)','Global coefficient','Relative (G)',...
    'G = bp^2 / (bp^2 + sigma_pi,e^2 / n)',...
    'psyrat_rel_sing',...
    'Formula Guide -> Run Formula',...
    'Implemented',...
    'Uses optional item SD (i) to separate sigma_i^2 from wp^2';...
    ...
    't2_icc_rel','2','One-facet (p x i)','ICC','Relative',...
    'ICC_rel = bp^2 / (bp^2 + sigma_pi,e^2)',...
    'psyrat_rel_sing',...
    'Formula Guide -> Run Formula',...
    'Implemented',...
    'Relative ICC excludes sigma_i^2 when i is provided';...
    ...
    't2_icc_abs','2','One-facet (p x i)','ICC','Absolute',...
    'ICC_abs = bp^2 / (bp^2 + sigma_pi,e^2 + sigma_i^2)',...
    'psyrat_rel_sing',...
    'Formula Guide -> Run Formula',...
    'Implemented',...
    'Absolute ICC maps to bp^2 / (bp^2 + wp^2)';...
    ...
    't2_cut_d','2','One-facet (p x i)','Cut-score coefficient','Absolute (D)',...
    'CutD = (bp^2 + (mu-cut)^2) / (bp^2 + (mu-cut)^2 + err_abs)',...
    'psyrat_cutscore_sing',...
    'Formula Guide -> Run Formula',...
    'Implemented',...
    'Criterion is entered as cut';...
    ...
    't3_rel_d','3','Two-facet (p x i x o)','CE/CS/CES coefficient','Absolute (D)',...
    'D = universe / (universe + abs_error)',...
    'psyrat_rel_trt',...
    'TRT startview + Formula Guide -> Run Formula',...
    'Implemented',...
    'reltype selects CE/CS/CES';...
    ...
    't3_rel_g','3','Two-facet (p x i x o)','CE/CS/CES coefficient','Relative (G)',...
    'G = universe / (universe + rel_error)',...
    'psyrat_rel_trt',...
    'TRT startview + Formula Guide -> Run Formula',...
    'Implemented',...
    'reltype selects CE/CS/CES';...
    ...
    't3_icc_abs','3','Two-facet (p x i x o)','ICC (CE/CS/CES)','Absolute',...
    'ICC = universe / (universe + abs_error) at obs=1, nocc=1',...
    'psyrat_rel_trt (obs=1,nocc=1)',...
    'Formula Guide -> Run Formula',...
    'Implemented',...
    'Uses reltype and absolute error';...
    ...
    't3_icc_rel','3','Two-facet (p x i x o)','ICC (CE/CS/CES)','Relative',...
    'ICC = universe / (universe + rel_error) at obs=1, nocc=1',...
    'psyrat_rel_trt (obs=1,nocc=1)',...
    'Formula Guide -> Run Formula',...
    'Implemented',...
    'Uses reltype and relative error';...
    ...
    't3_cut_d','3','Two-facet (p x i x o)','Cut-score coefficient','Absolute (D)',...
    'Cut = (universe + (mu-cut)^2) / (universe + (mu-cut)^2 + abs_error)',...
    'psyrat_cutscore_trt',...
    'Formula Guide -> Run Formula',...
    'Implemented',...
    'Supports reltype and criterion (cut)';...
    ...
    't6_diff1_d','6','Difference score one-facet','Difference reliability','Absolute (D)',...
    'DiffD = uni_diff / (uni_diff + abs_error_diff)',...
    'psyrat_diffrel',...
    'Sing diff startview + Formula Guide -> Run Formula',...
    'Implemented',...
    'Supports optional residual covariance for concurrent measures';...
    ...
    't6_diff1_g','6','Difference score one-facet','Difference reliability','Relative (G)',...
    'DiffG = uni_diff / (uni_diff + rel_error_diff)',...
    'psyrat_diffrel',...
    'Sing diff startview + Formula Guide -> Run Formula',...
    'Implemented',...
    'Absolute/relative set by est';...
    ...
    't6_diff2_d','6','Difference score two-facet','Difference reliability CE/CS/CES','Absolute (D)',...
    'Diff = uni_diff / (uni_diff + abs_error_diff)',...
    'psyrat_diffrel_trt',...
    'Formula Guide -> Run Formula',...
    'Implemented',...
    'Uses reltype and supports residual covariance';...
    ...
    't6_diff2_g','6','Difference score two-facet','Difference reliability CE/CS/CES','Relative (G)',...
    'Diff = uni_diff / (uni_diff + rel_error_diff)',...
    'psyrat_diffrel_trt',...
    'Formula Guide -> Run Formula',...
    'Implemented',...
    'Uses reltype and supports residual covariance';...
    ...
    %--- Dynamic/conditional reliability (Rast & Clayson in press, analyses 11-22).
    %paper_table is the non-numeric token 'R&C' so the Rocha sing/trt filters
    %(which key on {2,3,6}) exclude these rows; the 'dynrel' filter keeps them.
    'dyn_sigma_z','R&C','Dynamic/conditional (Rast & Clayson)','Conditional residual SD','Scale model',...
    'sigma_pi,e(z) = exp(alpha + b_sigma . X(z))',...
    'psyrat_rel_dynrel',...
    'Reference (Show Usage); estimated via Specify Inputs',...
    'Implemented',...
    'Location-scale residual; X(z)=[z1] (1-D) or [z1 z2 z1*z2] (2-D); typical person delta_p=0';...
    ...
    'dyn_g','R&C','Dynamic/conditional (Rast & Clayson)','Conditional coefficient','Relative (G)',...
    'G(z) = bp^2 / (bp^2 + sigma_pi,e(z)^2 / n'')',...
    'psyrat_rel_dynrel',...
    'Reference (Show Usage); estimated via Specify Inputs',...
    'Implemented',...
    'Reliability as a function of standardized z; reuses psyrat_rel_sing per z';...
    ...
    'dyn_d','R&C','Dynamic/conditional (Rast & Clayson)','Conditional coefficient','Absolute (D)',...
    'D(z) = bp^2 / (bp^2 + (sigma_pi,e(z)^2 + sigma_i^2) / n'')',...
    'psyrat_rel_dynrel',...
    'Reference (Show Usage); estimated via Specify Inputs',...
    'Implemented',...
    'D adds the trial main effect sigma_i^2; G excludes it (as Rocha Table 2)';...
    ...
    'dyn_icc_rel','R&C','Dynamic/conditional (Rast & Clayson)','Conditional ICC','Relative',...
    'ICC_rel(z) = bp^2 / (bp^2 + sigma_pi,e(z)^2)',...
    'psyrat_rel_dynrel',...
    'Reference (Show Usage); estimated via Specify Inputs',...
    'Implemented',...
    'Single-observation conditional ICC (n''=1)';...
    ...
    'dyn_icc_abs','R&C','Dynamic/conditional (Rast & Clayson)','Conditional ICC','Absolute',...
    'ICC_abs(z) = bp^2 / (bp^2 + sigma_pi,e(z)^2 + sigma_i^2)',...
    'psyrat_rel_dynrel',...
    'Reference (Show Usage); estimated via Specify Inputs',...
    'Implemented',...
    'Single-observation conditional ICC (n''=1); absolute adds sigma_i^2';...
    ...
    'dyn_diff_g','R&C','Dynamic/conditional difference (Rast & Clayson)','Conditional difference reliability','Relative (G)',...
    'DiffG(z) = uni_diff / (uni_diff + rel_error_diff(z))',...
    'psyrat_diffrel',...
    'Reference (Show Usage); estimated via Specify Inputs',...
    'Implemented',...
    'Difference variants apply the conditional residual to psyrat_diffrel (cases 12/15/...)';...
    ...
    'dyn_diff_d','R&C','Dynamic/conditional difference (Rast & Clayson)','Conditional difference reliability','Absolute (D)',...
    'DiffD(z) = uni_diff / (uni_diff + abs_error_diff(z))',...
    'psyrat_diffrel',...
    'Reference (Show Usage); estimated via Specify Inputs',...
    'Implemented',...
    'Absolute adds the difference trial (and, with occasions, occasion) error terms';...
    ...
    'dyn_rescor','R&C','Dynamic/conditional difference (Rast & Clayson)','Residual correlation','Covariance',...
    'rho_e,12 (Gaussian, shared); rho_e,12(copula) (gamma cut, 19/20); SD(rho_e,s) (per-subject)',...
    'psyrat_dynrel_summary',...
    'Reference (Show Usage); estimated via Specify Inputs',...
    'Implemented',...
    ['Concurrent residual correlation for co-occurring events (cases 17-22). Under the Gaussian '...
    'family rho_e,12 is the observed-scale residual correlation; the gamma modular cut designs '...
    '(19/20) report rho_e,12(copula), the LATENT-normal Gaussian-copula correlation of the '...
    'PIT-transformed residuals - a different estimand, hence the distinct symbol. Per-subject '...
    'rho adds the between-person SD'];...
    ...
    %--- Nonparallel splits, observed design (Rocha Tables 4/5; analyses 23/24).
    %paper_table tokens '4'/'5' keep these out of the Rocha sing/trt filters
    %(which key on {2}/{3}/{6}); the 'splits' filter keeps them. Estimated
    %data-driven via Specify Inputs (the n_i/weight column + Nonparallel). The
    %parallel splits path (splits=2) reuses the Table 2/3 rows above unchanged.
    't4_d','4','Splits one-facet p x (i:s)','Global coefficient','Absolute (D)',...
    'D = sig_p^2 / (sig_p^2 + sig_ps^2/ns + sig_s^2/ns + sig_err^2/(ns*nbar_i))',...
    'psyrat_splits_summary',...
    'Splits startview + Specify Inputs (n_i column, Nonparallel)',...
    'Implemented',...
    'Exact; reuses psyrat_rel_sing with SD-scaled residual (nbar_i = harmonic mean of n_i); observed design only';...
    ...
    't4_g','4','Splits one-facet p x (i:s)','Global coefficient','Relative (G)',...
    'G = sig_p^2 / (sig_p^2 + sig_ps^2/ns + sig_err^2/(ns*nbar_i))',...
    'psyrat_splits_summary',...
    'Splits startview + Specify Inputs (n_i column, Nonparallel)',...
    'Implemented',...
    'Downward-biased LOWER BOUND: split means lump sigma_(i:s) into sig_err (gbias-flagged)';...
    ...
    't4_sem','4','Splits one-facet p x (i:s)','SEM','Absolute & Relative',...
    'SEM_abs = sqrt((sig_ps^2 + sig_s^2 + sig_err^2/nbar_i)/ns); SEM_rel drops sig_s^2',...
    'psyrat_splits_summary',...
    'Splits startview + Specify Inputs (n_i column, Nonparallel)',...
    'Implemented',...
    'Absolute SEM exact; relative SEM is an upper bound (mirror of t4_g)';...
    ...
    't5_d','5','Splits two-facet p x (i:s) x o','CE/CS/CES coefficient','Absolute (D)',...
    'D = universe / (universe + abs_error)',...
    'psyrat_splits_summary',...
    'Splits startview + Specify Inputs (n_i column, Nonparallel)',...
    'Implemented',...
    'reltype selects CE/CS/CES; reuses psyrat_rel_trt; exact under trials-nested-in-occasions (derivation sec.4)';...
    ...
    't5_g','5','Splits two-facet p x (i:s) x o','CE/CS/CES coefficient','Relative (G)',...
    'G = universe / (universe + rel_error)',...
    'psyrat_splits_summary',...
    'Splits startview + Specify Inputs (n_i column, Nonparallel)',...
    'Implemented',...
    'LOWER BOUND (sig_err lumps sigma_(i:s)); gbias-flagged; reltype CE/CS/CES';...
    ...
    't5_sem','5','Splits two-facet p x (i:s) x o','SEM (CE/CS/CES)','Absolute & Relative',...
    'SEM = sqrt(error term per reltype); err = sqrt(sig_pos^2 + sig_err^2/nbar_i)',...
    'psyrat_splits_summary',...
    'Splits startview + Specify Inputs (n_i column, Nonparallel)',...
    'Implemented',...
    'Absolute SEM exact; relative SEM is an upper bound';...
    };

catalog = cell2table(rows,...
    'VariableNames',...
    {'formula_id','paper_table','design','coefficient','decision_type','formula_ascii',...
    'psyrat_function','gui_status','implementation_status','notes'});

switch lower(analysis)
    case {'sing','sing_sserr'}
        onefacet = ~cellfun(@isempty,strfind(lower(catalog.design),'one-facet'));
        keep = ismember(catalog.paper_table,{'2'}) | ...
            (strcmp(catalog.paper_table,'6') & onefacet);
        catalog = catalog(keep,:);
    case 'sing_diff'
        onefacet = ~cellfun(@isempty,strfind(lower(catalog.design),'one-facet'));
        keep = ismember(catalog.paper_table,{'2'}) | ...
            (strcmp(catalog.paper_table,'6') & onefacet);
        catalog = catalog(keep,:);
    case 'trt'
        twofacet = ~cellfun(@isempty,strfind(lower(catalog.design),'two-facet'));
        keep = ismember(catalog.paper_table,{'3'}) | ...
            (strcmp(catalog.paper_table,'6') & twofacet);
        catalog = catalog(keep,:);
    case 'dynrel'
        %dynamic/conditional reliability (Rast & Clayson); tagged paper_table 'R&C'
        keep = strcmp(catalog.paper_table,'R&C');
        catalog = catalog(keep,:);
    case 'splits'
        %nonparallel splits, observed design (Rocha Tables 4/5); tagged '4'/'5'
        keep = ismember(catalog.paper_table,{'4','5'});
        catalog = catalog(keep,:);
    case 'all'
        %no filtering
    otherwise
        error('varargin:analysis',... %Error code and associated error
            strcat('WARNING: analysis is invalid. Valid values are\n',...
            '''all'', ''sing'', ''sing_sserr'', ''sing_diff'', ''trt'', ''dynrel'', or ''splits''.\n'));
end

end
